### ISSUE TITLE
seems like new cms50d+ are 115200 baud as well (related to 4.6 version?)

### ISSUE THREAD

**Issue by Pagey** [YourBrain/Contec-Pulse-Oximeter-in-Matlab#1]
seems to work swell when set at this rate- thanks!

**Comment by InfantLab** [comment]
Thanks for letting me know

**Comment by Pagey** [comment]
I understand that for some 19,200 baud works also- perhaps depends on specific hardware; 
PS in HeartRateUSB_serial.m in line 153 please change to pause cause WaitSecs is in the PsychoToolBox which *_serial doesn't require-
Thanks dearly for the code!
